stages:
  - build
  - test
  - deploy

variables:
  JAVA_HOME: "/usr/lib/jvm/java-21-openjdk-amd64"

build_job:
  stage: build
  script:
    - chmod +x ./gradlew
    - ./gradlew clean build -x test -Dorg.gradle.java.home=$JAVA_HOME
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

test_job:
  stage: test
  script:
    - chmod +x ./gradlew
    - ./gradlew test -Dorg.gradle.java.home=$JAVA_HOME
  artifacts:
    when: always
    paths:
      - build/reports/tests/test/
    reports:
      junit: build/test-results/test/TEST-*.xml
    expire_in: 1 week
  except:
    - master

spotbugs_job:
  stage: test
  script:
    - chmod +x ./gradlew
    - ./gradlew spotbugsMain -Dorg.gradle.java.home=$JAVA_HOME
  artifacts:
    when: always
    paths:
      - build/reports/spotbugs/
    expire_in: 1 week

deploy_local_job:
  stage: deploy
  script:
    # 1. 生成されたjarファイルを配置フォルダへコピー（名前を app.jar に統一）
    - cp build/libs/*.jar /opt/acomo/app.jar

    # 2. サービスを再起動（古いプロセスが自動で停止し、新しいjarで立ち上がります）
    - sudo systemctl restart acomo
  only:
    - master
