spring:
  session:
    store-type: none
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5433/accommodation_tax_db
    username: postgres
    password: ${ACOMO_DB_PASSWORD:GEpassword}
    driver-class-name: org.postgresql.Driver

server:
  address: localhost
  tomcat:
    accesslog:
      enabled: true
      directory: ${ACOMO_LOG_PATH:C:/tomcat/logs}
      prefix: access_log
      suffix: .log
      rotate: true
      file-date-format: .yyyy-MM-dd
      max-days: 7

logging:
  file:
    name: ${ACOMO_LOG_PATH:C:/tomcat/logs}/application.log
  logback:
    rollingpolicy:
      max-history: 7
  level:
    jp.lg.asp: DEBUG
